version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: data for ex2 j17
    tables:
      - name: product
        identifier: raw_gz_product
        description: all the products that are sold by greenweez 
        columns:
          - name: products_id
            description: primary_key of the table
            tests:
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: the shipping for all the orders
        columns:
          - name: orders_id
            description: ID of the orders
            tests:
              - unique
      - name: sales
        identifier: raw_gz_sales
        description: sales of GW
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"

      - name: adwords
        identifier: raw_gz_adwords

      - name: bing
        identifier: raw_gz_bing

      - name: criteo
        identifier: raw_gz_criteo

      - name: facebook
        identifier: raw_gz_facebook
    
models:
  - name: sales
    tests:
    - unique:
        column_name: "(products_id||'-'||orders_id)"

